### ISSUE TITLE
Saving a User with no Roles leaves the tab blank

### ISSUE THREAD

**Issue by amondel2** [grails-plugins/grails-spring-security-ui#104]
Related to  #89 and #95

### Steps to Reproduce
I found this when adding a new tab and is related to issues #89 

1. search for a user
2. remove all the roles 
3. click update
4. on click the "Role" tab

### Expected Behaviour
1. A list of Roles with none checked should appear

### Actual Behaviour
2. The tab has no data

Tell us what happens instead

### Environment Information

- **Operating System**: Ubuntu latest
- **GORM Version:6.1.7.RELEASE
- **Grails Version (if using Grails): 3.3.1/3.3.0
- **JDK Version:1.8

### Example Application

- Use either the Extend or Simple code included in the plugin

**Comment by ddelponte** [comment]
I have a fix for this that's awaiting review and merge:  
https://github.com/grails-plugins/grails-spring-security-ui/pull/95

Once I resolve the conflicts I'll ping sergio to see if we can get this PR merged

**Comment by ddelponte** [comment]
Closing.  This is a duplicate of #89
