### ISSUE TITLE
No plugin [spring-security-ui-1.0-RC3] installed, cannot uninstall

### ISSUE THREAD

**Issue by StevenAppJob** [grails-plugins/grails-spring-security-ui#126]
Hi I am using JDK 1.8.0_281 with grails 2.5.6 version.

When I install the new plugin:
```
		compile ":spring-security-core:2.0-RC5"
		compile ":spring-security-ui:1.0-RC3"
```
it gives the warning :
```
Warning |
No plugin [spring-security-ui-1.0-RC3] installed, cannot uninstall
```
and error:

`/plugins/spring-security-ui/grails-app/controllers/grails/plugins/springsecurity/ui/RegisterController.groovy: 19: unable to resolve class org.codehaus.groovy.grails.commons.ApplicationHolder`

Thank you.

**Comment by puneetbehl** [comment]
It is unlikely to release a new version for Grails 2. Please use the latest version of the plugin with higher Grails releases. Also, Grails 2 and Grails 3 are end-of-support. Please read more information [here](https://grails.org/support-schedule.html)
