### ISSUE TITLE
Exception from UserController

### ISSUE THREAD

**Issue by paulcitarella** [grails-plugins/grails-spring-security-ui#17]
I have a clean grails 2.2 app with a few domain classes, and after adding the security UI plugin I'm getting the following exception when accessing /user.

| Error 2013-02-10 20:00:50,400 [http-bio-8080-exec-5] ERROR [/].[default]  - Servlet.service() for servlet [default] in context with path [] threw exception [org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grails.plugins.springsecurity.ui.UserController': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [grails.plugins.springsecurity.ui.UserController]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityUiService': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: net/sf/cglib/core/DebuggingClassWriter] with root cause
Message: net.sf.cglib.core.DebuggingClassWriter
   Line | Method
->> 202 | run              in java.net.URLClassLoader$1
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   190 | findClass        in java.net.URLClassLoader
|   306 | loadClass . . .  in java.lang.ClassLoader
|   247 | loadClass        in     ''
|    30 | getClassWriter . in net.sf.cglib.core.DefaultGeneratorStrategy
|    24 | generate         in     ''
|   216 | create . . . . . in net.sf.cglib.core.AbstractClassGenerator
|   144 | create           in net.sf.cglib.core.KeyFactory$Generator
|   116 | create . . . . . in net.sf.cglib.core.KeyFactory
|   108 | create           in     ''
|   104 | create . . . . . in     ''
|   196 | getBean          in grails.plugin.cache.web.filter.AbstractFilter
|   842 | lookupController in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|   176 | doFilter         in     ''
|    63 | doFilter . . . . in grails.plugin.cache.web.filter.AbstractFilter
|    80 | doFilterInternal in com.granicus.grails.plugins.cookiesession.CookieSessionFilter
|   886 | runTask . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
|   908 | run              in     ''
^   680 | run . . . . . .  in java.lang.Thread

The full app is available on Git Hub at https://github.com/grails-galahad/webapp/tree/security-ui.

**Comment by burtbeckwith** [comment]
Fixed in 1.0-RC3 and 3.0.0.M1
