### ISSUE TITLE
generateLink function should use grails.serverURL in configuration

### ISSUE THREAD

**Issue by rhodebump** [grails-plugins/grails-spring-security-ui#32]
This method should not be passing a "base" arg to the grails createLink function.  Doing this causes the link to not use the configured grails.serverURL

```
protected String generateLink(String action, linkParams) {
    createLink(base: "$request.scheme://$request.serverName:$request.serverPort$request.contextPath",
            controller: 'register', action: action,
            params: linkParams)
}
```

**Comment by ddelponte** [comment]
I think a good solution would be to modify the signature of the tag to accept an optional `absolute` attribute as defined at http://gsp.grails.org/latest/ref/Tags/createLink.html

If the `absolute` attribute resolves to `true`, then the value of the `grails.serverURL` will be used, else it will continue to function as it currently does.

**Comment by ddelponte** [comment]
code has been reviewed and merged.  closing.
