### ISSUE TITLE
Cannot install plugin

### ISSUE THREAD

**Issue by ManuelitoCalles** [grails-plugins/grails-spring-security-ui#50]
Hi everybody,
The following error is produced when applying changes to project structure:
Error |
Resolve error obtaining dependencies: Could not find artifact org.grails.plugins:spring-security-ui:jar:1.0-RC3 in grailsCentral (http://repo.grails.org/grails/plugins) (Use --stacktrace to see the full trace)
Error |
Resolve error obtaining dependencies: Could not find artifact org.grails.plugins:spring-security-ui:jar:1.0-RC3 in grailsCentral (http://repo.grails.org/grails/plugins) (Use --stacktrace to see the full trace)
Error |
Resolve error obtaining dependencies: Could not find artifact org.grails.plugins:spring-security-ui:jar:1.0-RC3 in grailsCentral (http://repo.grails.org/grails/plugins) (Use --stacktrace to see the full trace)
Error |
Could not find artifact org.grails.plugins:spring-security-ui:jar:1.0-RC3 in grailsCentral (http://repo.grails.org/grails/plugins)

Environment:
- Java 1.7
- Grails 2.3.8
- IntelliJ IDEA 15 as IDE

Dependency added to BuildConfig.groovy:
compile "org.grails.plugins:spring-security-ui:1.0-RC3"

Thanks in advance.

**Comment by Timzawrzzz** [comment]
I got it to install using their latest release:
compile "org.grails.plugins:spring-security-ui:3.0.0.M2"

**Comment by burtbeckwith** [comment]
@Timzawrzzz that's the version for Grails 3, the issue was raised against Grails 2

**Comment by burtbeckwith** [comment]
It's looking for a jar file, did you put the plugin dependency in the `dependencies` section? It has to be in the `plugins` section with the rest of the plugins.

**Comment by ddelponte** [comment]
Hi @ManuelitoCalles and thank-you for submitting this issue!

Did Burt's recommendations work for you?  Has this been resolved?

**Comment by ddelponte** [comment]
I'm opting to close this Issue because it is not reproducible.

@ManuelitoCalles  please contact me if this is is still an issue for you and you would like it reopened.

**Comment by arifulislam3010** [comment]
yes This is still an issue for me @ddelponte

**Comment by arifulislam3010** [comment]
ng process on monir-PC/172.168.0.53
Loading Grails 2.5.4
|Configuring classpath
Error |
Resolve error obtaining dependencies: Could not transfer artifact org.grails.plugins:tomcat:zip:7.0.55.3 from/to grailsCentral (https://repo.grails.org/grails/plugins): Received fatal alert: protocol_version (Use --stacktrace to see the full trace)
Error |
Resolve error obtaining dependencies: The following artifacts could not be resolved: cglib:cglib-nodep:jar:2.2.2, org.grails:grails-datastore-test-support:jar:1.0.2-grails-2.4, org.grails.plugins:scaffolding:zip:2.1.2, org.grails.plugins:cache:zip:1.1.8, org.grails.plugins:asset-pipeline:zip:2.5.7, org.grails.plugins:hibernate4:zip:4.3.10, org.grails.plugins:database-migration:zip:1.4.0, org.grails.plugins:jquery:zip:1.11.1: Could not transfer artifact cglib:cglib-nodep:jar:2.2.2 from/to grailsCentral (https://repo.grails.org/grails/plugins): Received fatal alert: protocol_version (Use --stacktrace to see the full trace)
Error |
Resolve error obtaining dependencies: The following artifacts could not be resolved: org.grails.plugins:scaffolding:zip:2.1.2, org.grails.plugins:cache:zip:1.1.8, org.grails.plugins:asset-pipeline:zip:2.5.7, org.grails.plugins:hibernate4:zip:4.3.10, org.grails.plugins:database-migration:zip:1.4.0, org.grails.plugins:jquery:zip:1.11.1: Could not transfer artifact org.grails.plugins:scaffolding:zip:2.1.2 from/to grailsCentral (https://repo.grails.org/grails/plugins): Received fatal alert: protocol_version (Use --stacktrace to see the full trace)
Error |
Resolve error obtaining dependencies: The following artifacts could not be resolved: org.grails.plugins:scaffolding:zip:2.1.2, org.grails.plugins:cache:zip:1.1.8, org.grails.plugins:asset-pipeline:zip:2.5.7: Could not transfer artifact org.grails.plugins:scaffolding:zip:2.1.2 from/to grailsCentral (https://repo.grails.org/grails/plugins): Received fatal alert: protocol_version (Use --stacktrace to see the full trace)
Error |
Could not transfer artifact org.grails.plugins:tomcat:zip:7.0.55.3 from/to grailsCentral (https://repo.grails.org/grails/plugins): Received fatal alert: protocol_version
|Run 'grails dependency-report' for further information.

**Comment by arifulislam3010** [comment]
I am new in grails i use grails-2.5.4 and jdk1.7.0_80 when i try to create a project it show this error

**Comment by ddelponte** [comment]
Here's a few suggestions/questions:

- does it work if you create a new grails project at the command line?
- have you tried removing `~/.grails/ivy-cache` and then create a new project?
- have you tried `grails clean` followed by `grails refresh-dependencies`?
- have you tried creating a new project with IntelliJ instead of GGTS?

**Comment by smakela** [comment]
This is just an ssl issue (TLS 1.2). Fix would be to upgrade your java version to 1.7.0_131 or above.
Also adding -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2 as parameter for example compile process workrs for me.

grails compile -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2

**Comment by ddelponte** [comment]
Thanks @smakela !  Closing

**Comment by jpozorio** [comment]
Compile with -Dhttps.protocols did have not worked for me.

That's what I did
https://github.com/grails/grails-core/issues/11082#issuecomment-943468796
