### ISSUE TITLE
I18n fields on forms

### ISSUE THREAD

**Issue by Szymon2603** [grails-plugins/grails-spring-security-ui#51]
I noticed that _labelCode_ in _SecurityUiTagLib_ generate wrong code (message key). It takes value pageScope.s2uiBeanType which returns a name of class with reference value (for example "code" -> "grails.plugin.springsecurity.ui.RegisterCommand@6f09b5e.username.label"). It blocks forms internationalization.

**Comment by ddelponte** [comment]
This should be resolved by PR https://github.com/grails-plugins/grails-spring-security-ui/pull/81

The same PR also resolves issue #56 

I will close this once the PR is merged

**Comment by ddelponte** [comment]
Closing.  The related PR was reviewed and merged
