### ISSUE TITLE
continuous-integration/travis-ci/pr — The Travis CI build failed

### ISSUE THREAD

**Issue by amondel2** [grails-plugins/grails-spring-security-ui#54]
All checks have failed
1 failing check
Details
continuous-integration/travis-ci/pr — The Travis CI build failed.  This seems to be for Pull request to the 1.x branch and started sometime around #34 opened on Nov 3, 2015.   

Getting error message that  Completed 32 spock tests, 32 failed in 1m 57s

| Server stopped

| Tests FAILED  - view reports in /home/travis/build/grails-plugins/grails-spring-security-ui/functional-test-app/target/test-reports.

When running test-app locally the test are successful though its only 7.

**Comment by amondel2** [comment]
Fixed with my latest Pull Request in Ticket #53 along with original issue to remove Validation Warning and ensure Validations are happening.

**Comment by burtbeckwith** [comment]
Thanks, I was planning on doing an updated release soon and I'll include this.

**Comment by sdelamo** [comment]
Travis build is now passing. However, I have annotated several tests with Spock `IgnoreIf`. Several functional tests need to be executed supplying  `geb.env` system property.
