### ISSUE TITLE
When generate war package,missing jquery.js

### ISSUE THREAD

**Issue by 350050183** [grails-plugins/grails-spring-security-ui#55]
I have a project with grails 3.1.9,when export WAR package,the minified javascrpit file did not include jquery.js file.

http://localhost:8080/xxx/assets/spring-security-ui-aef7a75c488ca87f11a386b856c55a1b.js
spring-security-ui.unminified.js:397 Uncaught ReferenceError: jQuery is not defined

And in spring-security-ui.unminified.js,the variables still there:
//=require jquery/jquery-${grails.plugin.springsecurity.ui.Constants.JQUERY_VERSION}.js
//=require jquery-ui/jquery-ui-${grails.plugin.springsecurity.ui.Constants.JQUERY_UI_VERSION}.js

In development environment it is OK.

How to fix it?

**Comment by burtbeckwith** [comment]
If you have an asset file in your app's grails-app/assets directory with the same name and location as one from a plugin it will override the plugin's, so you can create 3 files with hard-coded versions as a workaround until the next release of the plugin.

Create `grails-app/assets/javascripts/jquery.js` with contents:

    //=require jquery/jquery-2.1.4.js

and also `grails-app/assets/javascripts/jquery-ui.js` with

    //=require jquery-ui/jquery-ui-1.10.3.custom.js

and finally this CSS file `grails-app/assets/stylesheets/jquery-ui.css` with contents

    /*
     *= require smoothness/jquery-ui-1.10.3.custom.css
     */

**Comment by 350050183** [comment]
Thanks,it works!
