### ISSUE TITLE
Broken Images in HTML docs

### ISSUE THREAD

**Issue by rpalcolea** [grails-plugins/grails-spring-security-ui#58]
The HTML docs in http://grails-plugins.github.io/grails-spring-security-ui/v3/index.html have broken images.

<img width="1009" alt="screen shot 2016-08-26 at 4 17 15 pm" src="https://cloud.githubusercontent.com/assets/1625920/18022958/93da3786-6ba8-11e6-82f3-8e511cb4ffb1.png">

**Comment by sdelamo** [comment]
This is now fixed. Screenshots were not being copied to Github pages branch.
