### ISSUE TITLE
Error in Updating or deleting user

### ISSUE THREAD

**Issue by sakthisgit** [grails-plugins/grails-spring-security-ui#62]
While update or delete the users, it throws the following error

| Error 2016-12-16 19:07:53,874 [http-bio-8080-exec-11] ERROR ast.ErrorCounter  - line 1:8: unexpected token: in
| Error 2016-12-16 19:07:53,878 [http-bio-8080-exec-11] ERROR ast.ErrorCounter  - line 1:8: unexpected token: in
Message: unexpected token: in
    Line | Method
->>  915 | doCall               in grails.gorm.DetachedCriteria$_deleteAll_closure7
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    700 | doCall               in org.grails.datastore.gorm.GormStaticApi$_withDatastoreSession_closure23
|    302 | execute . . . . . .  in org.grails.datastore.mapping.core.DatastoreUtils
|     37 | execute              in org.grails.datastore.gorm.AbstractDatastoreApi
|    699 | withDatastoreSession in org.grails.datastore.gorm.GormStaticApi
|    914 | deleteAll            in grails.gorm.DetachedCriteria
|     73 | removeAll . . . . .  in in.cdac.chn.authentication.PersonAuthority
|    324 | $tt__updateUser      in grails.plugin.springsecurity.ui.SpringSecurityUiService
|     33 | updateUser . . . . . in grails.plugin.springsecurity.ui.strategy.DefaultUserStrategy
|     85 | doUpdate             in grails.plugin.springsecurity.ui.AbstractS2UiDomainController
|     32 | update . . . . . . . in grails.plugin.springsecurity.ui.UserController
|    198 | doFilter             in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . . . . . in grails.plugin.cache.web.filter.AbstractFilter
|     53 | doFilter             in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|     62 | doFilter . . . . . . in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|     59 | doFilter             in grails.plugin.springsecurity.web.SecurityRequestHolderFilter
|   1142 | runWorker . . . . .  in java.util.concurrent.ThreadPoolExecutor
|    617 | run                  in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . . . . . .  in java.lang.Thread
| Error 2016-12-16 19:07:53,966 [http-bio-8080-exec-11] ERROR errors.GrailsExceptionResolver  - QuerySyntaxException occurred when processing request: [POST] /stest/user/update - parameters:
version: 0
enabled: on
password: ***
_ROLE_USER: 
ROLE_USER: on
_accountExpired: 
ROLE_ADMIN: on
id: 2
_passwordExpired: 
_enabled: 
_accountLocked: 
username: test
_ROLE_ADMIN: 
unexpected token: in near line 1, column 8 [DELETE in.chn.authentication.PersonAuthority personAuthority WHERE (personAuthority.person=?)]. Stacktrace follows:
Message: unexpected token: in near line 1, column 8 [DELETE in.chn.authentication.PersonAuthority personAuthority WHERE (personAuthority.person=?)]
    Line | Method
->>  915 | doCall               in grails.gorm.DetachedCriteria$_deleteAll_closure7
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    700 | doCall               in org.grails.datastore.gorm.GormStaticApi$_withDatastoreSession_closure23
|    302 | execute . . . . . .  in org.grails.datastore.mapping.core.DatastoreUtils
|     37 | execute              in org.grails.datastore.gorm.AbstractDatastoreApi
|    699 | withDatastoreSession in org.grails.datastore.gorm.GormStaticApi
|    914 | deleteAll            in grails.gorm.DetachedCriteria
|     73 | removeAll . . . . .  in in.chn.authentication.PersonAuthority
|    324 | $tt__updateUser      in grails.plugin.springsecurity.ui.SpringSecurityUiService
|     33 | updateUser . . . . . in grails.plugin.springsecurity.ui.strategy.DefaultUserStrategy
|     85 | doUpdate             in grails.plugin.springsecurity.ui.AbstractS2UiDomainController
|     32 | update . . . . . . . in grails.plugin.springsecurity.ui.UserController
|    198 | doFilter             in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . . . . . in grails.plugin.cache.web.filter.AbstractFilter
|     53 | doFilter             in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|     62 | doFilter . . . . . . in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|     59 | doFilter             in grails.plugin.springsecurity.web.SecurityRequestHolderFilter
|   1142 | runWorker . . . . .  in java.util.concurrent.ThreadPoolExecutor
|    617 | run                  in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . . . . . .  in java.lang.Thread

Grails Version - 2.5.0
runtime ":hibernate4:4.3.8.1" // or ":hibernate:3.6.10.18"
compile "org.grails.plugins:spring-security-core:2.0.0"
compile "org.grails.plugins:spring-security-ui:1.0-RC3"

**Comment by sakthisgit** [comment]
application and plugin version:
========================
Grails Version - 2.5.0
runtime ":hibernate4:4.3.8.1" // or ":hibernate:3.6.10.18"
compile "org.grails.plugins:spring-security-core:2.0.0"
compile "org.grails.plugins:spring-security-ui:1.0-RC3"

**Comment by ddelponte** [comment]
@sakthisgit thank you for submitting this issue!

Are you able to provide more details or attach an example app which demonstrates the issue?

I have been unable to reproduce it.

**Comment by ddelponte** [comment]
I'm opting to close this Issue because it is not reproducible.

@sakthisgit please contact me if this is is still an issue for you and you would like it reopened.
