### ISSUE TITLE
s2ui-override errors in grails 3.2.2

### ISSUE THREAD

**Issue by wmunyan** [grails-plugins/grails-spring-security-ui#63]
Trying to execute the s2ui-override script in a grails 3.2.2 environment:

|Rendered template RegisterController.groovy.template to destination grails-app\controllers\myapp\register\RegisterController.groovy
Error |
Command [s2ui-override] error: class path resource [layouts/register.gsp] cannot be opened because it does not exist (Use --stacktrace to see the full trace)

I see other issues logged with this but there were no actual solutions/reasons posted.
Thanks for any help!

Grails 3.2.2.
Spring Security Core Plugin 3.1.1
Spring Security UI Plugin 3.0.0.M2

**Comment by apattanayak** [comment]
+1.
Grails 3.2.4
Spring Security Core Plugin 3.1.1
Spring Security UI Plugin 3.0.0.M2

**Comment by dekay2323** [comment]
+1 Same versions as above, tried copying the gsp from github does not work either

**Comment by pedromvaz** [comment]
+1
Grails v3.2.7
Spring Security Core Plugin v3.1.1
Spring Security UI Plugin v3.0.0.M2

**Comment by ultravi01** [comment]
+1

**Comment by neilabdev** [comment]
+1
Grails 2.3.8
Spring Security Core Plugin v3.1.1
Spring Security UI Plugin v3.0.0.M2

**Comment by piperpilot** [comment]
+1
Grails 3.2.4
I have tried many workarounds and really need to be able to render the register.gsp so that I can style it for my application.  If someone could look at this it would be great!

**Comment by bahmed73** [comment]
Hello:

I am having the same problem. I am using spring security ui 4, with grails 3. I then tried to modify RegisterController, but there are registrationcode strategy groovy files that are missing. I can't customize RegisterController either.

The s2ui-override is not generating .gsp files for register or registrationcode either.

Please help.

Thank you,
Bilal

**Comment by dekay2323** [comment]
Same problem

**Comment by dekay2323** [comment]
I got it to work, it is a bit of a pain, but you need to actually copy this file

https://github.com/grails-plugins/grails-spring-security-ui/blob/master/grails-app/views/layouts/register.gsp

Into the directory grails-app/register/layouts/

**Comment by bahmed73** [comment]
Hello:

Thank you for a quick response.

I tried this register.gsp file already. The issue is that with this code, if I deploy on tomcat, bundled with grails, i.e. grails prod run-app, it works fine.

If I bundle the war, grails prod package, and copy the war file into a separate tomcat installation, for production, and deploy it. Tomcat has it's own directory structure, I deploy the war in the ROOT folder. That's where this register.gsp doesn't work. 

I also tried to override the RegisterController.groovy, but still couldn't get it to work.

Please try to deploy on a tomcat installation and see if it works for you.

Thanks again,
Bilal

**Comment by sdelamo** [comment]
Fixed in 3.0.1

**Comment by bahmed73** [comment]
Validated. It worked on: 

spring-security-ui:3.0.2
spring-security-core:3.1.1

grails -version
3.2.6

Thank you!

**Comment by slillon** [comment]
Hi, I'm experiencing the same problem with 'spring-security-core', version: '3.2.3', 'org.grails.plugins:spring-security-ui:3.0.2' on grails 3.3.11

**Comment by bahmed73** [comment]
Hello,

It's working for me. Please see screen shot. When the plugin is working, the login form shows the tabs and buttons correctly to register. Please deploy on tomcat, and then to the /register link on your server.

Thanks,
Bilal
![register](https://user-images.githubusercontent.com/51631/66963985-0e41d980-f02a-11e9-9ea1-1f6031f51681.png)
