### ISSUE TITLE
Error in Role Delete

### ISSUE THREAD

**Issue by sakthisgit** [grails-plugins/grails-spring-security-ui#64]
While deleting the user Role, doesn't delete the records, rather it persist.

Grails Version - 2.5.0
runtime ":hibernate4:4.3.8.1" // or ":hibernate:3.6.10.18"
compile "org.grails.plugins:spring-security-core:2.0.0"
compile "org.grails.plugins:spring-security-ui:1.0-RC3"

**Comment by ddelponte** [comment]
@sakthisgit thank you for submitting this issue!

Are you able to provide more details or attach an example app which demonstrates the issue?

I have been unable to reproduce it.

**Comment by ddelponte** [comment]
I'm opting to close this Issue because it is not reproducible.

@sakthisgit please contact me if this is is still an issue for you and you would like it reopened.
