### ISSUE TITLE
Cannot override register action in RegisterController.

### ISSUE THREAD

**Issue by avscj** [grails-plugins/grails-spring-security-ui#65]
I am trying to override the RegisterController register action inside a Grails 3.2.2 plugin, but it seems it still goes to the original one. But if I publish the plugin locally and then use it in an app, it then works with my action, but my overridden gsp in not rendered. I have put more details on [Stackoverflow](http://stackoverflow.com/questions/41797782/grails-3-2-2-spring-security-ui-override-registercontroller-not-working)

Could I get any help?

On another topic, I am also experiencing the same issue as: https://github.com/grails-plugins/grails-spring-security-ui/issues/63

**Comment by ddelponte** [comment]
@avscj thank you for reporting this issue!

It looks like both issue #63 and the issue reported on stackoverflow have been resolved.

Are you able to confirm this issue has been resolved?  

Thanks!

**Comment by ddelponte** [comment]
Closing because I believe this to be resolved.

More details are available at https://stackoverflow.com/questions/41797782/grails-3-2-2-spring-security-ui-override-registercontroller-not-working

**Comment by avscj** [comment]
Yes, this is fixed. Would be good if the documentation at https://grails-plugins.github.io/grails-spring-security-ui/latest/#s2ui-override-script mentions that you need to namespace your controllers if you need to override them

**Comment by ddelponte** [comment]
@avscj great idea!

Would you be so kind as to create a new issue outlining your documentation request or provide a PR that includes your desired change.  

Thank-you
