### ISSUE TITLE
S2UI  Submit Button is not working in grails

### ISSUE THREAD

**Issue by imadi** [grails-plugins/grails-spring-security-ui#66]
I have given the following code in the gsp `<s2ui:submitButton elementId='create' class="btn btn-primary"  messageCode='default.button.create.label'/>`. But submit button is not working. When debugged a bit I got to know that javascript 

`\$("#$elementId").button();
	\$('#$elementId').bind('click', function() {
		document.forms.${formName}.submit();
	})` is not getting loaded.

**Comment by bahmed73** [comment]
Hello:

I am having the same problem. I am using spring security ui 4, with grails 3. I then tried to modify RegisterController, but there are registrationcode strategy groovy files that are missing. I can't customize RegisterController either. 

The s2ui-override is not generating .gsp files for register or registrationcode either.

Please help.

Thank you,
Bilal

**Comment by sdelamo** [comment]
With the latest version, @bahmed73 `s2ui-override` command should be generating the correct *.gsp files for register or registration code.

**Comment by ddelponte** [comment]
@imadi and @bahmed73 , are you able to confirm this fixed in the latest version?

**Comment by bahmed73** [comment]
Hi @ddelponte, I am able to get it to work:

spring-security-ui:3.0.2
spring-security-core:3.1.1

grails -version
3.2.6

Thank you!

![image](https://user-images.githubusercontent.com/51631/31032699-f1d38a56-a511-11e7-9f74-69567bfe0a95.png)

**Comment by ddelponte** [comment]
Thank-you for such a quick response, @bahmed73 !

I will go ahead and close this issue  ✨
