### ISSUE TITLE
Can't build app with JDK 7

### ISSUE THREAD

**Issue by piperpilot** [grails-plugins/grails-spring-security-ui#72]
I'm trying to build a war for deployment on openshift.  Openshift supports Java 6 and 7.  When I try to build using a Java 7 JDK, I get the following:

grails/plugin/springsecurity/ui/RegistrationCodeController : Unsupported major.minor version 52.0

Is Java 8 really required?  Is there a way around this.  I am banging my head against the wall trying to get my grails 3.1.16 app to work.

Thanks!

**Comment by ddelponte** [comment]
@piperpilot I've confirmed that I can successfully build a war file using a more recent version of grails:

1. Java 7
2. grails-3.3.6
3. grails-spring-security-core:3.2.2
4. grails-spring-security-ui:3.1.2

Is this still an issue for you?

**Comment by piperpilot** [comment]
Its not important to me.  I switched over to Amazon and am running on a newer version of Tomcat and Java...I never could get the Java 7 version to work I don't believe.

**Comment by ddelponte** [comment]
@piperpilot thank-you for the follow-up.  

I'm going to close this issue.
