### ISSUE TITLE
Stale documentation on http://grails-plugins.github.io/grails-spring-security-ui/ 

### ISSUE THREAD

**Issue by oliver-was-here** [grails-plugins/grails-spring-security-ui#73]
The link to "Current documentation" is a year out of date. 

Felt it was worth noting as dependency resolution between then and now has significantly changed with only the one liner `'compile 'org.grails.plugins:spring-security-ui:3.0.2' making` making life a whole lot easier from an integration standpoint.

Updating the site could save some time for future users. Keep up the great work :)

**Comment by sdelamo** [comment]
I've updated the docs installation section. 

https://grails-plugins.github.io/grails-spring-security-ui/latest/#installation

Please, reopen if you consider the issue unresolved.
