### ISSUE TITLE
Unable to bring up grails application - Grails 3.3.0 RC1

### ISSUE THREAD

**Issue by sredrouthu** [grails-plugins/grails-spring-security-ui#74]
Unable to start the grails application with spring-security-core plugin 3.2.0.M1 and spring-security-ui 3.0.2 .

build.gradle has the following:
    compile 'org.grails.plugins:spring-security-ui:3.0.2'
    compile 'org.grails.plugins:spring-security-core:3.2.0.M1'

Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.embedded.FilterRegistrationBean

**Comment by sdelamo** [comment]
Thanks for reporting an issue.

Version 3.1.1 is compatible with Grails 3.3.x

compile 'org.grails.plugins:spring-security-ui:3.1.1'

Please, reopen the issue if you are still experiencing issues.
