### ISSUE TITLE
grails 3.3.0 with spring-security-ui no error but the bootstrap is no longer working

### ISSUE THREAD

**Issue by vi7Ch** [grails-plugins/grails-spring-security-ui#77]
@sdelamo Thanks for maintaining this grails landmark plugin.
my app compile and run without error but when I open the login page, all the bootstrap layout has gone.
I've tested with
    compile 'org.grails.plugins:spring-security-ui:3.1.0'
and    
    compile files ("lib/spring-security-ui-3.1.0.jar")

Do I need to inject other dependency for bootstrap support ?

Thanks.

**Comment by sdelamo** [comment]
I am working on this. Stayed tuned
