### ISSUE TITLE
User update removes all user roles

### ISSUE THREAD

**Issue by AlexBoulyga** [grails-plugins/grails-spring-security-ui#89]
When updating a user, it removes all role associations, unless the user has none, than it does work.

Meaning you always have to update the user twice (re-selecting all roles).
I noticed that behaviour for versions:
3.1.0
3.1.1

I believe this is due to grails 3.3 taking hibernate a little different.
Currently this plugin simply deletes all UserRole and recreates the new ones.
However, as the whole function is inside a @transactional statement, this does not work as planned.
Even when setting flush to true, it only creates the diff of roles.
This means, even though having deleted (and flushed), the old userRoles are still recognized on "create" and are not beeing re-created.

I have played around a little bit and found only one working solution:
Do not delete all, check what to delete and what to create

I don't know if this is the "clean" way to do it, however I will make a PR with this change, and you can decide.

If it's not ok, please implement a different fix, because as of now, this is a major problem for us.
You want to change the user password -> roles get deleted.

EDIT:
I have also noticed, that with the current master, it is not possible to update users at all.

Setup:
Groovy 2.4.11
Java 1.8.0_161
grails 3.3.0
gradle 3.5
gorm 6.1.6.RELEASE

BR,
Alex

**Comment by AlexBoulyga** [comment]
This PR should fix the ROLE problem, not the general saving problem however (mentioned below).
I tested the same code changes with 3.1.1 tag and am going to use that in my grails application for now.

I will also come back to the general saving error!

**Comment by ddelponte** [comment]
I have used @AlexBoulyga 's PR for inspiration and created a new at https://github.com/grails-plugins/grails-spring-security-ui/pull/95 which has been assigned to @sdelamo for review.
