### ISSUE TITLE
All pages vulnerable to CSRF

### ISSUE THREAD

**Issue by jdega33** [grails-plugins/grails-spring-security-ui#9]
Every form in this UI is vulnerable to cross site request forgery. How can it be fixed? Is the application supposed to be automatically fixing all CSRF even in the transitive closure of plugins, via some filter/HTML modification hook? I'm new to Grails so I don't know how this is normally done (if at all).

This can trivially be fixed by wrapping every controller action in withForm.

```
class SomeController {
    def someAction = {
        // do stuff
    }
}
```

becomes

```
class SomeController {
    def someAction = {
        withForm {
            // do stuff
        }
    }
}
```

... then change all the GSP forms to attach the token.
`<g:form method="post">`
becomes
`<g:form method="post" useToken="true">`

**Comment by edwardotis** [comment]
2016 - Is this plugin still wide open to CSRF attack?

**Comment by ddelponte** [comment]
Code has been reviewed and manually squashed/merged into master by @sdelamo
