### ISSUE TITLE
grails.plugin.springsecurity.ui.gsp.layoutRegister not working as expected

### ISSUE THREAD

**Issue by oliver-was-here** [grails-plugins/grails-spring-security-ui#91]
This may not be an issue so much as an unfortunate side-effect of Grails that might use some documentation to help other unfortunate souls down the road.

### Issue
Unfortunately, I do not believe `grails.plugin.springsecurity.ui.gsp.layoutRegister` works as expected in the event that a custom `RegisterController` is implemented. It appears that Grails magic template resolver will always attempt to apply the `layout/yourControllerName.gsp` layout to the "concrete" view of a given action for `YourControllerNameController.groovy`. In my case, it resolves to the `layout/register.gsp` defined in the SpringSecurityUi plugin if it does not find the layout defined within my project's `layout` directory.

### Steps to reproduce
• Create a new project
• Inherit from `springsecurity.ui.RegisterController` with `your.custom.RegisterController`
• Create `layouts/custom.gsp`
• Create a custom `register/register.gsp` that applies the `custom.gsp` layout
• Set `grails.plugin.springsecurity.ui.gsp.layoutRegister: custom` in `application.yml`
• navigate to `/register/register`
Expected -> Grails will apply `custom.gsp` to the `register.gsp` view
Actual -> Grails applies `custom.gsp` and `register.gsp` view

### Likely Workaround
I believe the solution would be to create a uniquely named controller. I did not go this route as I was lazy at the time and did not want to explicitly "blacklist" all the out-of-the-box `RegisterController` endpoints. I have not yet refactored and tested this, but putting this here for posterity.

**Comment by ddelponte** [comment]
@oliver-was-here thanks for submitting this issue!

Do you happen to recall what version of `grails`, `spring-security-core` and `spring-security-ui` you were using when you discovered this issue?

**Comment by oliver-was-here** [comment]
@ddelponte Ha, whoops, sounds like relevant info.

grails: `3.2.11`
security-core: `3.1.2`
spring-security-ui: `3.0.2`

**Comment by ddelponte** [comment]
@oliver-was-here , I have been unable to duplicate your issue.  Layouts are working as expected.

I've attached a sample app configured as you have outlined:
# Views
## views/register/register.gsp
Applies the `register` layout

# Layouts
layouts/custom.gsp
layouts/register.gsp

# Config
## conf/application.yml
added the line `grails.plugin.springsecurity.ui.gsp.layoutRegister: custom`
This will automatically apply the `custom` layout to any register views which have not been overriden.

# How to test

1. run the app
1. navigate to http://localhost:8080/register
1. login with admin/password
1. verify the view is:
![image](https://user-images.githubusercontent.com/95676/39640634-3c592890-4f91-11e8-815c-e28b4307a8c1.png)
1. modify the layout utilized by `views/register/register.gsp` to be `custom`
5.1 `<meta name="layout" content="custom"/>`
1. refresh the page and verify the view is:
![image](https://user-images.githubusercontent.com/95676/39640845-edeebaac-4f91-11e8-9f54-4e2279c7e24e.png)
1. delete the view `views/register/register.gsp`
1. refresh the page and verify the view is:
![image](https://user-images.githubusercontent.com/95676/39640919-20aa82fa-4f92-11e8-8dbe-cd1bacf58949.png)

The `application.yml` config of `grails.plugin.springsecurity.ui.gsp.layoutRegister: custom` will only be applied to registration pages that have not been copied over locally.

Please let me know if the attached app works for you as I have outlined above.

Thanks!

[issue91.zip](https://github.com/grails-plugins/grails-spring-security-ui/files/1975276/issue91.zip)

**Comment by ddelponte** [comment]
Closing.  Unable to reproduce
